PokerAppMVC/Controllers/InputsController.cs
using PokerAppMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PokerAppMVC.Controllers
{
    public class InputsController : Controller
    {

        public ActionResult Index()
        {
            return View(new Input());
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Calculate(Input input)
        {
            if (input.SmallBlind <= 0)
                ModelState.AddModelError("SmallBlind", "Not a valid value");

            if (input.BigBlind <= 0)
                ModelState.AddModelError("BigBlind", "Not a valid value");

            if (input.Stack <= 0)
                ModelState.AddModelError("Stack", "Not a valid value");

            if (input.Players <= 0)
                ModelState.AddModelError("Players", "Not a valid value");

            if (input.Opponents <= 0)
                ModelState.AddModelError("Opponents", "Not a valid value");

            if (input.SmallBlind > input.BigBlind)
                ModelState.AddModelError("BigBlind", "BigBlind must be bigger than SmallBlind");

            if (input.Ante.HasValue && input.Ante.Value > input.SmallBlind)
                ModelState.AddModelError("Ante", "Ante must be lower than SmallBlind");

            if (input.Opponents <= 0)
                ModelState.AddModelError("Opponents", "Opponents must be bigger than Player");

            if (ModelState.IsValid == false)
                return View("Index", input);

            return RedirectToAction("Index", "Results", input);
        }


    }
}

PokerAppMVC/Controllers/ResultsController.cs
using PokerAppMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PokerAppMVC.Controllers
{
    public class ResultsController : Controller
    {
        public ActionResult Index(Input input)
        {
            var result = input.Calculate();

            return View(result);
        }
    }
}

PokerAppMVC/Views/Inputs/Index.cshtml
@model PokerAppMVC.Models.Input

@{
    ViewBag.Title = "Input Page";
}

<h2>Input</h2>


@using (Html.BeginForm("Calculate", "Inputs")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SmallBlind, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SmallBlind, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.SmallBlind, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BigBlind, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BigBlind, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.BigBlind, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ante, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ante, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.Ante, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stack, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stack, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Stack, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Players, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Players, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Players, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opponents, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opponents, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Opponents, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Calculate" class="btn btn-default">
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

PokerAppMVC/Views/Results/Index.cshtml
@model PokerAppMVC.Models.Result

@{
    ViewBag.Title = "Results";
}

<h2>Results</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CPR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CPR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CSI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CSI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PN)
        </dd>
    </dl>
    <hr />
    <dl class="dl-horizontal">
        <dt>Table</dt>
        <dd>
            <table class="table-bordered">
                @{List<string> rows = new List<string>() { "A", "K", "Q", "J", "T", "9", "8", "7", "6", "5", "4", "3", "2" };}
                @for (int row = 0; row < 13; row++)
                {
                    <tr>
                        
                        @for (int col = 0; col < 13; col++)
                        {                                
                            if (Model.TableValidated[row, col])
                            {
                                <td style="background-color:#73F55C" title="@Model.TableWeights[row,col].ToString()">@rows[row]@rows[col]</td>
                            }
                            else if (Model.TableWeights[row,col].IsNegative)
                            {
                                <td style="background-color:#B94A48" title="@Model.TableWeights[row,col].ToString()">@rows[row]@rows[col]</td>
                            }
                            else
                            {
                                <td style="background-color:#CCC" title="@Model.TableWeights[row,col].ToString()">@rows[row]@rows[col]</td>
                            }
                        }
                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Back", "Index", "Inputs")
</p>

PokerAppMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MVC</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MVC - Poker APP", "Index", "Inputs", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - B & D Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>